### ISSUE TITLE
Feed of future events for tags

### ISSUE THREAD

**Issue by sknebel** [indieweb/events.indieweb.org#1]
https://events.indieweb.org/tag/hwc contains all events ever with this tag, and is sorted furthest into the future first. I'd like a page like this, but sorted like the front page: only events in the future, sorted soonest first.

**Comment by aaronpk** [comment]
I was thinking about this while building it, and opted for the default "blog-style" tag page first. But now I'm thinking that actually the default tag page should show just upcoming events with that tag, and you have to navigate elsewhere to see the full archive of events with that tag.

**Comment by aaronpk** [comment]
Ok this is done! Tag pages now show only upcoming events. At the bottom is a link to a page that shows all upcoming and past events with that tag.

I think this is the right decision because most of the time people will be looking for upcoming events.
